# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure rumqttd paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ rumqttd_uid }}"
    group: "{{ rumqttd_gid }}"
  with_items:
    - "{{ rumqttd_base_path }}"
    - "{{ rumqttd_config_path }}"

- name: Ensure rumqttd container image is pulled
  community.docker.docker_image:
    name: "{{ rumqttd_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ rumqttd_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else rumqttd_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure rumqttd container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ rumqttd_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure rumqttd systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/rumqttd.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ rumqttd_identifier }}.service"
    mode: "0644"
