# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---


- name: Perform rumqttd installation tasks
  block:
    - name: Validate rumqttd configuration
      when: rumqttd_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install rumqttd
      when: rumqttd_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-rumqttd
    - install-all
    - install-rumqttd

- name: Perform rumqttd uninstallation tasks
  block:
    - name: Uninstall rumqttd
      when: not rumqttd_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-rumqttd
