# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform rumqttd installation tasks
  when: rumqttd_enabled | bool
  tags:
    - setup-all
    - setup-rumqttd
    - install-all
    - install-rumqttd
  block:
    - name: Validate rumqttd configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install rumqttd
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform rumqttd uninstallation tasks
  when: not rumqttd_enabled | bool
  tags:
    - setup-all
    - setup-rumqttd
  block:
    - name: Uninstall rumqttd
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
