---

- name: Fail if required rumqttd settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - rumqttd_container_http_host_bind_port
